version: '3.6'

services:
  web-1:
    image: nginx:latest
    hostname: web-1
    container_name: web-1
    ports:
      - "8081:80"
    env_file: configuration.env
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/proxy.conf:/etc/nginx/conf.d/default.conf

  web-2:
    image: nginx:latest
    hostname: web-2
    container_name: web-2
    ports:
      - "8082:80"
    env_file: configuration.env
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app-1
    container_name: app-1
    ports:
      - "9000:9000"
    env_file: configuration.env
    working_dir: /var/www
    volumes:
      - ./php/index.php:/var/www/index.php

